FROM golang:1.20 as build
WORKDIR /issuer_crawler

# Copy dependencies list
COPY go.mod go.sum ./
# Build with optional lambda.norpc tag
COPY ./issuer_crawler/cmd/main.go .
COPY ./issuer_crawler ./issuer_crawler
COPY ./utils ./utils
RUN go build -tags lambda.norpc -o main main.go
# Copy artifacts to a clean image
FROM public.ecr.aws/lambda/provided:al2023
COPY --from=build /issuer_crawler/main ./main
ENTRYPOINT [ "./main" ]